- name: installing nginx
  hosts: web
  become: yes
  tasks: 
  - name: install nginx
    apt:
      name: nginx
      state: latest
  - name: start nginx
    apt:
      name: nginx
      state: started     
    