- name: variables playbook
  hosts: localhost
  vars: #variables declaration
   Team: "mumbai"
   Player: "rohit"
   No: "45"
  tasks:
  - name: print from vars
    ansible.builtin.debug:
     msg: "This is {{Player}}"