- name: variables 
  hosts: localhost
  vars:
    place: "newyork"
    city: "manhatton"
  tasks:
  - name: print info
    ansible.builtin.debug:
     msg: "Hi iam from {{place}}, {{city}}"
      
       