- name: variables playbook
  hosts: localhost
  vars: #variables declaration
   team: "mumbai"
   name: "rohit"
   no: "45"
  tasks:
  - name: print from vars
    ansible.builtin.debug:
      print: "Hi, this is{{name}} from team {{team}} and jersy number {{no}}.""     
      