#ansible   
- name: variable preference
  hosts: web
  vars:
    declare: "I am from play"
  vars_files:
  - vars.file
  vars_prompt:
    - name: declare
      prompt: Enter your msg
      private: false
  tasks:
    - name: checking prefernce
      # vars:
      #   declare: I am from task
      ansible.builtin.debug:
        msg: You are from {{declare}}

#variables prefer order
#args
#task