- name: variables 
  hosts: localhost
  vars:
    place: "newyork"
    city: "manhatton"
  tasks:
  - name: print info
    ansible.builtin.debug:
     msg: "Hi iam from {{place}}, {{city}}"
  - name: print info
    vars:
      place: "texas"
      city: "dallas"
    ansible.builtin.debug:
     msg: "Hi iam from {{place}}, {{city}}"   
      
       