- name: variables from arguments
  hosts: localhost
  tasks: 
  - name: print info
    ansible.builtin.debug:
      msg: "hi iam from {{team}},{{role}}" #passing variables from argument -e "team=ISM role=SRE"