- name: filters
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "the value {{ team | default('mumbai') }}"

- name: uppercase
  hosts: localhost
  vars:
    team: "Mumbai"
  tasks: 
  - name: convert to upper
    ansible.builtin.debug:
      msg: "{{ team | upper }}" 

- name: lowercase
  hosts: localhost
  vars:
    team: "Mumbai"
  tasks: 
  - name: convert to upper
    ansible.builtin.debug:
      msg: "{{ team | lower }}"  

- name: remove duplicates
  hosts: localhost
  vars:
    team: [ 1, 2, 3, 4, 5, 2, 3,]
  tasks: 
  - name: convert to upper
    ansible.builtin.debug:
      msg: "{{ team | unique }}"  

- name: min and max
  hosts: localhost
  vars:
    ages: [ 15, 25, 30 ]
  tasks: 
  - name: print min and max
    ansible.builtin.debug:
      msg: "max age :: {{ ages | max }} , min age :: {{ ages | min}}" 

- name: converting dict to items
  hosts: localhost
  vars:
    teams:
      mumbai: rohit
      hyd: cummins
      rajsthan: sanju
  tasks: 
  - name: convert to dict2itemsr
    ansible.builtin.debug:
      msg: "before converting {{teams}}"
  - name: converting dict2items
    ansible.builtin.debug:
      msg: "after converting {{ teams | dict2items }}"     
      
           
          