- name: loops to install packages and delete at a time 
  hosts: localhost
  become: yes
  tasks:
  - name: installing packages via loops
    dnf:
     name: "{{ item }}"
     state: absent #latest to install
    loop:
    - mysql
    - nginx 


   