- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: installing packages via loops
    dnf:
     name: "{{ item }}"
     state: latest
    loop:
    - { name: 'mysql', state: 'latest'}
    - { name: 'nginx' , state: 'absent'}
     


   