- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: installing packages via loops
    dnf:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'latest' }
    - { name: 'nginx' , state: 'absent' }
     


   